### ISSUE TITLE
Error Launching.

### ISSUE THREAD

**Issue by 5H2** [challacade/legend-of-lua#5]
Error

src/startup/gameStart.lua:18: module 'libraries/hump/vector' not found:
no field package.preload['libraries/hump/vector']
no 'libraries/hump/vector' in LOVE game directories.
no file 'libraries/hump/vector' in LOVE paths.
no file '.\libraries/hump/vector.lua'
no file 'C:\Program Files\LOVE\lua\libraries/hump/vector.lua'
no file 'C:\Program Files\LOVE\lua\libraries/hump/vector\init.lua'
no file '.\libraries/hump/vector.dll'
no file 'C:\Program Files\LOVE\libraries/hump/vector.dll'
no file 'C:\Program Files\LOVE\loadall.dll'

Traceback

[love "callbacks.lua"]:228: in function 'handler'
[C]: in function 'require'
src/startup/gameStart.lua:18: in function 'gameStart'
main.lua:8: in function 'load'
[love "callbacks.lua"]:136: in function <[love "callbacks.lua"]:135>
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by challacade** [comment]
Fixed by putting in libraries in full, rather than referenced. Thanks for the heads-up on this.

**Comment by 5H2** [comment]
Alright! Launches perfectly! But, slight issue, I was unable to figure out
the controls, I had to red through the code to figure it out (Sword, Bombs,
Boomerang, Ect..) So I recommend making a pause menu where you can see
controls, change volume, ect..

Just my personal Opinion, Love the vids, Keep it up!
